#!/bin/bash

#qu=compute # levante
qu=12h   # albedo
ensdir="fdirty-wide"
runme -rs -q ${qu} -w 06:00:00 -n par/basalmixing.toml -o output/${ensdir}/combined -p ctrl.likelihood=combined
runme -rs -q ${qu} -w 06:00:00 -n par/basalmixing.toml -o output/${ensdir}/kr81 -p ctrl.likelihood=kr81
