#!/bin/bash

runme -rs -q compute -w 06:00:00 -n par/basalmixing.toml -o output/ens-combined -p ctrl.likelihood=combined
runme -rs -q compute -w 06:00:00 -n par/basalmixing.toml -o output/ens-kr81 -p ctrl.likelihood=kr81
